In [1]:
import numpy as np

with open('D:/2024-2025/python nâng cao/17a2-vd\chương_3/bài tập chương 3/heights_1.txt','r',encoding='utf-8-sig') as f:
    height =f.readlines()
    height = list(height[0].split(','))
    list_height=list(map(lambda x:float(x),height))
print(list_height)
with open('D:/2024-2025/python nâng cao/17a2-vd/chương_3/bài tập chương 3/heights_1.txt','r',encoding='utf-8-sig') as f:
    weight =f.readlines()
    weight = list(weight[0].split(','))
    list_weight=list(map(lambda x:float(x),weight))

<>:3: SyntaxWarning: invalid escape sequence '\c'
<>:3: SyntaxWarning: invalid escape sequence '\c'
C:\Users\OS\AppData\Local\Temp\ipykernel_10856\196569651.py:3: SyntaxWarning: invalid escape sequence '\c'
  with open('D:/2024-2025/python nâng cao/17a2-vd\chương_3/bài tập chương 3/heights_1.txt','r',encoding='utf-8-sig') as f:


[74.0, 74.0, 72.0, 72.0, 73.0, 69.0, 69.0, 71.0, 76.0, 71.0, 73.0, 73.0, 74.0, 74.0, 69.0, 70.0, 73.0, 75.0, 78.0, 79.0, 76.0, 74.0, 76.0, 72.0, 71.0, 75.0, 77.0, 74.0, 73.0, 74.0, 78.0, 73.0, 75.0, 73.0, 75.0, 75.0, 74.0, 69.0, 71.0, 74.0, 73.0, 73.0, 76.0, 74.0, 74.0, 70.0, 72.0, 77.0, 74.0, 70.0, 73.0, 75.0, 76.0, 76.0, 78.0, 74.0, 74.0, 76.0, 77.0, 81.0, 78.0, 75.0, 77.0, 75.0, 76.0, 74.0, 72.0, 72.0, 75.0, 73.0, 73.0, 73.0, 70.0, 70.0, 70.0, 76.0, 68.0, 71.0, 72.0, 75.0, 75.0, 75.0, 75.0, 68.0, 74.0, 78.0, 71.0, 73.0, 76.0, 74.0, 74.0, 79.0, 75.0, 73.0, 76.0, 74.0, 74.0, 73.0, 72.0, 74.0, 73.0, 74.0, 72.0, 73.0, 69.0, 72.0, 73.0, 75.0, 75.0, 73.0, 72.0, 72.0, 76.0, 74.0, 72.0, 77.0, 74.0, 77.0, 75.0, 76.0, 80.0, 74.0, 74.0, 75.0, 78.0, 73.0, 73.0, 74.0, 75.0, 76.0, 71.0, 73.0, 74.0, 76.0, 76.0, 74.0, 73.0, 74.0, 70.0, 72.0, 73.0, 73.0, 73.0, 73.0, 71.0, 74.0, 74.0, 72.0, 74.0, 71.0, 74.0, 73.0, 75.0, 75.0, 79.0, 73.0, 75.0, 76.0, 74.0, 76.0, 78.0, 74.0, 76.0, 72.0, 74.0, 76.0, 74.

#### 1. Tạo numpy array arr height từ list height

In [5]:
arr_height = np.array(list_height)
arr_height

array([74., 74., 72., ..., 75., 75., 73.])

#### 2. Tạo numpy array arr_ weight từ list weight

In [6]:
arr_weight = np.array(list_weight)
arr_height

array([74., 74., 72., ..., 75., 75., 73.])

#### 3. Cho hệ số quy đổi từ inch sang m là 0.0254, tạo arr height_m dựa trên công thức: arr_height * hệ số quy đổi

In [7]:
arr_height_m = np.array([i *0.0254 for i in arr_height])
arr_height_m

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

#### 4. Cho hệ số quy đổi từ pound sang kg là 0.453592, tạo arr_weight_kg dựa trên công thức: arr_weight * hệ số quy đổi

In [8]:
arr_weight_kg  =np.array([i* 0.453592 for i in arr_weight])
arr_weight_kg

array([33.565808, 33.565808, 32.658624, ..., 34.0194  , 34.0194  ,
       33.112216])

#### 5. Tính BMI của arr height_m và arr_weight kg theo công thức BMI = Cần nặng / (Chiều cao * Chiều cao), và lưu vào arr_bmi

In [9]:
arr_BMI = np.array([])
for i in range(0,len(arr_height)):
    arr_BMI = np.append(arr_BMI,arr_weight_kg[i]/(arr_height_m[i]*arr_height_m[i]))

#### 6. Cho biết giá trị cân nặng ở vị trí index = 50 trong arr_weight_kg

In [10]:
print(arr_weight_kg[50])

33.112216


#### 7. Tạo art_height_m_100 gồm các phần tử có vị trí index từ 100 đến 110 (lấy cả index 110) trong arr_height_m

In [12]:
arr_height_m_100 = arr_height_m[100:111]
arr_height_m_100

array([1.8542, 1.8796, 1.8288, 1.8542, 1.7526, 1.8288, 1.8542, 1.905 ,
       1.905 , 1.8542, 1.8288])

#### 8. Cho biết các cầu thủ bóng chày có bmi < 21 trong arr_bmi

In [13]:
bmi_less_than_21 = arr_BMI[arr_BMI<21]
print("Các cầu thủ có BMI < 21:", bmi_less_than_21)

Các cầu thủ có BMI < 21: [9.50093252 9.50093252 9.76484731 ... 9.37425342 9.37425342 9.63108228]


#### 9. Cho biết chiều cao trung bình và cân nặng trung bình của các cầu thủ

In [14]:
average_height = np.sum(arr_height_m)/arr_height_m.size
print("chiều cao trung bình:",average_height)
average_weight = np.sum(arr_weight_kg)/arr_weight_kg.size
print("cân nặng trung bình",average_weight)

chiều cao trung bình: 1.8717172413793102
cân nặng trung bình 33.42503806896551


#### 10. Cho biết chiều cao và cân nặng lớn nhất của các cầu thủ

In [15]:
max_height = np.sort(arr_height_m)[-1]
print("chiều cao lớn nhất",max_height)
max_weight = np.sort(arr_weight_kg)[-1]
print("cân nạng cao nhất",max_weight)

chiều cao lớn nhất 2.1082
cân nạng cao nhất 37.648136


#### 11. Cho biết chiều cao và cân nặng nhỏ nhất của các cầu thủ

In [16]:
min_height = np.sort(arr_height_m)[0]
print("chiều cao nhỏ nhất",min_height)
min_weight = np.sort(arr_weight_kg)[0]
print("cân nạng nhỏ nhất",min_weight)

chiều cao nhỏ nhất 1.7018
cân nạng nhỏ nhất 30.390664
